name: jigongjia
description: 格格记工 - 工人记工模块
publish_to: 'none'
version: 1.1.4+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  provider: ^6.1.0
  image_picker: ^1.0.0
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.12.0
  share_plus: ^7.2.0
  uuid: ^4.2.0
  fl_chart: ^0.68.0
  permission_handler: ^11.0.0
  file_picker: ^8.0.0
  image: ^4.5.4
  path: ^1.9.1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
